query GetProductById($id: ID!) {
  products(filters: { id: { eq: $id } }) {
    data {
      id
      attributes {
        name
        description
        price
        sale_price
        images {
          data {
            attributes {
              name
              url
              alternativeText
              caption
              formats
            }
          }
        }
        category {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
