mutation registerUser($username: String!, $email: String!, $password: String!) {
  register(input: { username: $username, email: $email, password: $password }) {
    jwt
    # user {
    #   id
    #   username
    #   email
    # }
  }
}
